### ISSUE TITLE
发现几个bug

### ISSUE THREAD

**Issue by azhangmeng** [willian12345/websqlWrapper#5]
提几个bug：
1、方法save是根据key判断更新或保存，传入key值时，如果为字符串，条件语句应该加入单引号，修改如下： if(Utils.is.String(key)){
                where = key + "='" + values[key] + "'";
                sql +=' WHERE '+ where;
            }
方法update同上修改
2、方法count，统计记录数目，如果记录为null会报错，即r.length报错；
其他建议：
1、所有条件where后默认添加1=1；
2、添加分页的实现

**Comment by willian12345** [comment]
ok
